### PR TITLE
Add applied energistics 2 API 

### PR DESCRIPTION
**Pull request by timoheijne**
Add AE2 api for typescript.

Not every function has been tested to be completely honest. 
But so far everything seems to work peachy :D

### CODE REVIEW

**Comment by Exeteres** [comment]
Thanks for the PR!

Is there the good reason to use snake case for interface names?
It is very inconsistent with the other codebase.
I highly recommend using standard naming conventions, even if the documentation states otherwise!

**Comment by timoheijne** [comment]
I indeed did it because the ocdocs indicated the me_controller.
But surely not bound to it. i'll make the adjustment

**Comment by Exeteres** [comment]
image

I think we should create a namespace for it:
```ts
namespace ME {
    interface ImportBus { ... }
}
```

And use it like `ME.ImportBus`.

**Comment by timoheijne** [comment]
Ah yeah, that's cleaner indeed.

(also first time creating a type definition file. So enough to learn :D)

**Comment by Exeteres** [comment]
Mention when you're done. I will need to move some declarations to make this even cleaner.

**Comment by timoheijne** [comment]
I am done! Feel free to!

**Comment by Exeteres** [comment]
Did I understand correctly that all provided components are available as properties of the `component` object and through the `component.get` and `component.getPrimary` functions?

**Comment by timoheijne** [comment]
That's correct indeed. 
to get the controller I currently use `component.getPrimary("me_controller")`

**Comment by Exeteres** [comment]
In this case I need some time to refactor the component api to allow extending it type from another (ae2) library.
I will try to do it tomorrow. I hope this is not critical for you.

**Comment by timoheijne** [comment]
Is all fine! I have a local working version setup anyway. 
When you're done making the changes I can just modify it to comply wit the changes then

**Comment by Exeteres** [comment]
Now it should be available in npm!

**Pull request merged**
